
"""Add scan table

Revision ID: e4559338a6a8
Revises: 98191086381e
Create Date: 2026-02-17 10:34:23.801871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4559338a6a8'
down_revision = '98191086381e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('scan_type', sa.Enum('SUBDOMAIN', 'PORT', 'SERVICE', 'WEB', 'VULNERABILITY', 'SSL', 'FULL', name='scantype'), nullable=False),
    sa.Column('target', sa.String(length=500), nullable=False),
    sa.Column('tool_used', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='scanstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('results', sa.Text(), nullable=True),
    sa.Column('raw_output', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_celery_task_id'), 'scan', ['celery_task_id'], unique=False)
    op.create_index(op.f('ix_scan_id'), 'scan', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_id'), table_name='scan')
    op.drop_index(op.f('ix_scan_celery_task_id'), table_name='scan')
    op.drop_table('scan')
    # ### end Alembic commands ###
